### ISSUE TITLE
Post-receive git hook reloads nginx and runs composer install even if not changed

### ISSUE THREAD

**Issue by l3ku** [Seravo/wordpress#102]
This happens every time during git hook execution:
```
Seravo: composer.json was updated, installing...
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
Class WordPress\Installer is not autoloadable, can not call post-install-cmd script
Seravo: Nginx configs were changed, reloading nginx...
testing nginx configuration...
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
PHP7.3 mode enabled
Restarting nginx...
Nginx restarted!
```

**Comment by ottok** [comment]
What does `git hook execution` mean? What command shall I run to reproduce it?

Maybe https://github.com/Seravo/wordpress/blob/master/scripts/git-hooks/post-receive#L25 isn't listing correct files. This by the way differs from https://github.com/Seravo/wordpress/blob/master

**Comment by l3ku** [comment]
In this case `git hook execution` means that I have symlinked from `/data/wordpress/scripts/git-hooks/post-receive` to `/data/wordpress/.git/hooks/post-merge`, so when I SSH into the server and run `git pull origin master` the hook script will be run. However, every time I do this regardless of wether the commits contain `composer.json` modifications or nginx configuration changes, both `composer install` and `wp-restart-nginx` are run.

At a glance I think it is because `COMPOSER_CHANGED` is not defined if no modifications to the relevant files are made and this somehow evaluates to true in the check.

**Comment by tnottu** [comment]
Another thing to check might be this if statement:
https://github.com/Seravo/wordpress/blob/08f5a760587f3f325608101cb4069cf72b992365/scripts/git-hooks/post-receive#L31

With the single `=` characters this line will always evaluate to `true`. I'm not a bash expert but seems that double `==` checks if variable is defined also?

This modified line has worked for us (without defining the variables first) `if [ "$line" == "composer.json" ] || [ "$line" == "composer.lock" ]; then`

Just another solution, don't know if there's any benefit compared to yours.

**Comment by ottok** [comment]
Interestingly we have had these single quotes in our codebase since 2015 without anybody noticing and apparently the post-receive hook has worked OK in production anyway:
![image](https://user-images.githubusercontent.com/668724/58937162-4bdc4f00-877a-11e9-95c2-0580a7a8864f.png)

We will review these.

**Comment by tnottu** [comment]
My understanding is that the post-receive hook has only _seemed_ to work, because the condition always evaluated to true. It triggered the actions when it shouldn't have. The problem i mentioned in #103 probably wasn't noticed because `composer install` was executed every time, whether it was in the last commit or not.

**Comment by tnottu** [comment]
Oh, i just realized we had other changes too, to make our fix work:

https://github.com/Seravo/wordpress/blob/08f5a760587f3f325608101cb4069cf72b992365/scripts/git-hooks/post-receive#L39

Our check looks like this: `if [ "$COMPOSER_CHANGED" ]; then`

And:

https://github.com/Seravo/wordpress/blob/08f5a760587f3f325608101cb4069cf72b992365/scripts/git-hooks/post-receive#L44

-> `if [ "$NGINX_CHANGED" ]; then`

I think those changes are what check if the variable is defined first.
