### ISSUE TITLE
Investigate official Google WordPress plugin as default plugin option

### ISSUE THREAD

**Issue by nuuttitoivola** [Seravo/wordpress#104]
Google is about to release a new WordPress plugin called Site Kit: 
- https://sitekit.withgoogle.com/ 
- https://sitekit.withgoogle.com/news/site-kit-developer-preview/
- https://github.com/google/site-kit-wp 

I think we should look into this, after it's released, if it is in some way better than the one we're currently installing by default for Google Analytics purposes.
Currently we use the plugin: https://wordpress.org/plugins/google-analytics-dashboard-for-wp/

**Comment by ottok** [comment]
This is a good idea. I had this on my TODO but haven't got around to it. Good is somebody else gets to it sooner. Evaluating a new plugin is also a good blog topic.

**Comment by ottok** [comment]
Another potential one for default plugin could be https://wordpress.org/plugins/native-image-lazy-loading/

Currently the latest version of the Google Analytics Dashboard for WP (GADWP) is a bit annoying as it displays this notice on _every_ page of WP-admin:
![image](https://user-images.githubusercontent.com/668724/65241850-50403400-daed-11e9-8b97-4b41bbd4962e.png)

**Comment by nuuttitoivola** [comment]
Google Site Kit is now published:
- https://sitekit.withgoogle.com/news/site-kit-is-now-available-for-all-wordpress-sites/ 
- https://wordpress.org/plugins/google-site-kit/
