### ISSUE TITLE
Command to pull WordPress core version from production

### ISSUE THREAD

**Issue by TeemuSuoranta** [Seravo/wordpress#106]
The vagrant box comes with commands to pull database and plugins from production site. It would be nice to be able to also pull the WordPress core version (and update it to composer.json like plugins if possible). The core version in composer.json will easily lag behind of production and it is thus easy to accidentally run locally different version of core than in production.

In most of the cases you could just run `wp core update` locally because generally the production sites use the newest version although there can be issues with automated tests for example that will make core to be some minor updates behind.

**Comment by ottok** [comment]
Like wp-pull-everything?

**Comment by TeemuSuoranta** [comment]
There could be combined pull, too.

For `wp-pull-production-core` could basically connect via ssh, run `wp core version`, return the value and run `wp core update --version={version}` if it's difficult to do via rsync. Though there could be errors if running `wp core version` outputs some warnings and not just the version.

**Comment by ottok** [comment]
Do you still think this is useful? We have only got one request for this, but it is not a big thing, I could implement it if you want.

**Comment by TeemuSuoranta** [comment]
I think there are a few use cases for this and maybe more than ever when Gutenberg releases are not always completely backwards compatible and introduce big changes. Sure, this is not a feature that people who are building new sites will need but if I'm doing some changes to a site that is 3-4 years old, it would be a little more foolproofing as I can make sure that the WP version matches. Then again if there is a test breaking update that I'd like to manually update, I could manually update it on development environment and revert the version via this command.

There might be some technical difficulties implementing this that I cannot see but I do think that this would complete the various pull commands offered.

**Comment by ottok** [comment]
Latest Docker version has it now and next Vagrant box will have it as well:
```
vagrant@development:~$ wp-pull-production-core 
==> Production site WP version: 5.3.3
Downloading WordPress 5.3.3 (en_US)...
md5 hash verified: 222287b4856c753dbe4e3ed8699e2535
Cleaning up files...
No files found that need cleaning up.
Success: WordPress downloaded.
```
