### ISSUE TITLE
Update npm dev dependencies and Gulpfile

### ISSUE THREAD

**Issue by l3ku** [Seravo/wordpress#107]
According to git, nobody has touched these files for 3 years. That is a very long time in the speed which the node.js ecosystem evolves, so we should probably update the `package.json` dependencies and make improvements to `gulpfile.js`. We might also want to consider if there are some better alternatives to Gulp that have emerged during this time.

**Comment by ottok** [comment]
Agreed! Merging/testing #97 would also fit this context.
