### ISSUE TITLE
Vagrantfile: running "composer install" post-install script on Windows causes symlink(): Protocol error

### ISSUE THREAD

**Issue by l3ku** [Seravo/wordpress#114]
Error caused by attempting to run Composer on Windows via WSL causes a `symlink(): Protocol error` during the post-installation WP content symlinking script:
```
==> wordpress-box: > WordPress\Installer::symlinkWPContent                  
==> wordpress-box: Script WordPress\Installer::symlinkWPContent handling the post-install-cmd event terminated with an exception      
==> wordpress-box:
==> wordpress-box:
==> wordpress-box:   [ErrorException]
==> wordpress-box:   symlink(): Protocol error
```
Maybe Composer should always be run inside Vagrant/Docker instead on Windows machines?

**Comment by ottok** [comment]
Is this perhaps a variant on #121?

**Comment by ottok** [comment]
No further information on this one, closing as "won't fix".
