### ISSUE TITLE
Git hook emits "remote: error: Could not access 'HEAD'"

### ISSUE THREAD

**Issue by ottok** [Seravo/wordpress#117]
Users are reporting they are seeing this error message when pushing to git:
```
git push production
...
Writing objects: 100% (23/23), 2.87 KiB | 0 bytes/s, done.
Total 23 (delta 19), reused 0 (delta 0)
remote: error: Could not access 'HEAD'
To ssh://<redacted>/data/wordpress
e34d073..4f156ba master -> master
```

I suspect there is something going on with line `changed_files=$(git diff --name-only --diff-filter=ACM HEAD HEAD^)`.

**Comment by l3ku** [comment]
Would probably make sense to also solve https://github.com/Seravo/wordpress/issues/103 at the same time when looking through this.
