### ISSUE TITLE
vagrant up/reload just keeps adding new entries to /etc/hosts

### ISSUE THREAD

**Issue by ottok** [Seravo/wordpress#12]
Hello!

Every time I run 'vagrant up' or 'vagrant reload' or similar commands, the IP address of the Vagrant box changes (in fact a new Virtualbox network interface is created every time). My /etc/hosts gets populated with ever new lines. As only the first line matches, it means that in effect my browser never finds the Vagrant server unless I manually keep cleaning up the /etc/hosts file over and over again.

This is extremely annoying an probably impossible to debug to those who don't know where to look.

**Comment by anttiviljami** [comment]
Are you running vagrant destroy to automatically clean up your hostsfile? Works fine for me on both OS X and cygwin. 

If you don't destroy your vagrant boxes properly, the auto-cleanup won't happen and you will leave entries in your hostsfile. In that case, just manually delete all the vagrant hostsfile entries and run vagrant up again.

**Comment by ottok** [comment]
Keep open until resolved and 'vagrant reload' and 'vagrant suspend + vagrant up' works as expected in Vagrant normally

**Comment by ottok** [comment]
´´´
$ grep dev /etc/hosts
192.168.205.242  wordpress-wp-dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  www.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  webgrind.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  adminer.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  mailcatcher.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  browsersync.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  info.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  wordpress.seravo.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f

$ vagrant status
Current machine states:

default                   saved (virtualbox)

To resume this VM, simply run `vagrant up`.

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'seravo/wordpress' is up to date...
==> default: Resuming suspended VM...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for host entries
==> default: adding to (/etc/hosts) : 192.168.193.24  wordpress-wp-dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
==> default: adding to (/etc/hosts) : 192.168.193.24  wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
==> default: adding to (/etc/hosts) : 192.168.193.24  www.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
==> default: adding to (/etc/hosts) : 192.168.193.24  webgrind.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
==> default: adding to (/etc/hosts) : 192.168.193.24  adminer.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
==> default: adding to (/etc/hosts) : 192.168.193.24  mailcatcher.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
==> default: adding to (/etc/hosts) : 192.168.193.24  browsersync.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
==> default: adding to (/etc/hosts) : 192.168.193.24  info.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
==> default: adding to (/etc/hosts) : 192.168.193.24  wordpress.seravo.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
[sudo] password for otto: 
==> default: Running triggers after up...
checking for composer... yes
Warning: This development build of composer is over 30 days old. It is recommended to update it by running "/usr/lib/composer/composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing wpackagist-plugin/polylang (1.7.5)
    Loading from cache

  - Installing wpackagist-plugin/posts-to-posts (1.6.3)
    Loading from cache

Generating autoload files
==> default: Executing remote command "wp-vagrant-import-db"...
==> default: Success: Database was imported correctly!
==> default: Remote command execution finished.
==> default: Executing remote command "sudo service nginx restart"...
==> default:  * Restarting nginx nginx
==> default:    ...done.
==> default: Remote command execution finished.
==> trigger: Visit your site: http://wordpress.dev

$ grep dev /etc/hosts
192.168.205.242  wordpress-wp-dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  www.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  webgrind.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  adminer.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  mailcatcher.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  browsersync.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  info.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.205.242  wordpress.seravo.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.193.24  wordpress-wp-dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.193.24  wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.193.24  www.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.193.24  webgrind.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.193.24  adminer.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.193.24  mailcatcher.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.193.24  browsersync.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.193.24  info.wordpress.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
192.168.193.24  wordpress.seravo.dev  # VAGRANT: 8bbfed5e31d34876e5fe883137c521bf (default) / 1c3d76ce-4db7-4960-852c-7876ef0bb75f
´´´

The problem is with the Vagrantfile that always adds a new virtual network interface without removing the old one. Running 'vagrant destroy' in between will clean up the hosts file but still leaves the virtualbox network interface behind.

Please check how this is solved in other Vagrantfiles so that creating and deleting the virtual network interface is reliable.

**Comment by onnimonni** [comment]
@ottok Which OS are you using?

**Comment by onnimonni** [comment]
We could change the Vagrantfile to give a static ip address for example in the config.yml so even though /etc/hosts would have multiple entries they would be the same.

I didn't want to hardcode the IP-address in case people are using multiple boxes at the same time:
https://github.com/Seravo/wordpress/blob/master/Vagrantfile#L36-L38

**Comment by ottok** [comment]
Vagrant 1.7.2 on Ubuntu 12.04.5 LTS

**Comment by ottok** [comment]
Is it possible to write in the Vagrantfile the host line adding so that it is done only when a new box is bootstrapped and not otherwise? Or that before creating new virtual network interfaces the previous ones (and /etc/hosts entries) would be deleted? Is it possible to trigger the same cleanup code which is run in 'vagrant destroy' to avoid getting doulbe /etc/hosts entries?

Or can you force in the Vagrantfile that 'vagrant destroy' is always run before the rest of the Vagrantfile executes? As I understood this is what you are now doing, always running "vagrant destroy && vagrant up" so maybe the easiest (but a bit stupid) solution is to embed "vagrant destroy" inside the "vagrant up" (=Vagranfile stanzas) command

**Comment by anttiviljami** [comment]
really what it should do, is during any vagrant up/halt/destroy/reload invocation, it should check whether the vagrant boxes in the hostsfile are actually running and remove / add entries accordingly.

I guess we need to fix this upstream https://github.com/cogitatio/vagrant-hostsupdater

**Comment by onnimonni** [comment]
It's possible but this is a upstream error rather than in our config: https://github.com/cogitatio/vagrant-hostsupdater/issues/67

Can you try following:
1. Remove all vagrant related entries
2. Change the ip address to static ip in Vagrantfile
3. add this into your Vagrantfile:
`config.hostsupdater.remove_on_suspend = true`

**Comment by anttiviljami** [comment]
Seems to be done in this fork: https://github.com/weynhamz/vagrant-hostsupdater/commit/69df40a0e75946be61465d9954c0ac74b923a25f

**Comment by onnimonni** [comment]
@ottok @anttiviljami this fork seems to do it. I'm just not sure how to use that and I don't have linux machine where to try this out

**Comment by ottok** [comment]
Have you ever noticed that upstream is dead, last updated in 2013 and has since 12 open PRs? https://github.com/cogitatio/vagrant-hostsupdater/pulls

After browsing the 53 forks at https://github.com/cogitatio/vagrant-hostsupdater/network I found this which looks like it could be the solution https://github.com/weynhamz/vagrant-hostsupdater/commit/69df40a0e75946be61465d9954c0ac74b923a25f

**Comment by cgsmith** [comment]
@ottok working to remedy the upstream issue! I'll keep this issue updated if I hear something.

**Comment by cgsmith** [comment]
@ottok I pulled this in and will be testing it shortly.

**Comment by ottok** [comment]
This has been fixed for a long while already.
