### ISSUE TITLE
Mailcatcher is not available in docker

### ISSUE THREAD

**Issue by k1sul1** [Seravo/wordpress#124]
http(s)://mailcatcher.pakettikauppa.local/ doesn't work, while https://pakettikauppa.local/ works fine. Same behaviour after running `docker-compose pull`.

**Comment by ottok** [comment]
Avahi didn't register properly it seems. You can try an alternative address `/.seravo/mailcatcher/`. On my test machine however that seems broken as well.. looking into it
![image](https://user-images.githubusercontent.com/668724/71089304-3c1dd880-21a9-11ea-8ca5-65694b0f3b7a.png)

**Comment by ottok** [comment]
As a temporary workaround you can add to you `/etc/hosts` a line pointing the Docker IP address to `mailcatcher.pakettikauppa.local`

**Comment by k1sul1** [comment]
I tried that yesterday, didn't work either. `/.seravo/mailcatcher/` is broken for me too.

**Comment by ottok** [comment]
Latest Docker version has this now fixed.
