### ISSUE TITLE
Error in post-receive hook: fatal: not a git repository

### ISSUE THREAD

**Issue by JoosuaKoskinen** [Seravo/wordpress#133]
A customer noticed the following error while pushing to production after installing the post-receive hook:
```
remote: Seravo: running post-receive git hook
remote: fatal: not a git repository: '.'
remote: Seravo: Flushing all caches...
```

**Comment by tnottu** [comment]
Probably due to removal of the `GIT_DIR` in this commit 
https://github.com/Seravo/wordpress/commit/e59b4f082e962ee33da2c2bb4979929d03dbc782#diff-8023fc70ccc637626d348363aec8ae0dL22

**Comment by JoosuaKoskinen** [comment]
Using `GIT_DIR` indeed fixes it.

**Comment by ottok** [comment]
Can you @JoosuaKoskinen fix this and document properly GIT_DIR so nobody in the future removes it thinking it has no purpose (as on local runs it has no purpose, there is only the remote push use case I think?)

**Comment by JoosuaKoskinen** [comment]
Fixed in https://github.com/Seravo/wordpress/commit/45e7d9df2d8bd90b82e476ebcb65eb8cd884dc96
