### ISSUE TITLE
Funny directory permissions

### ISSUE THREAD

**Issue by ottok** [Seravo/wordpress#14]
While browsing inside the image (with 'vagrant ssh') I noticed that most of the file permissions in /data look weird:

```
vagrant@wordpress-wp-dev:/data/wordpress$ ll
total 112
drwxrwxrw- 1 vagrant vagrant  4096 May 26 18:39 ./
drwxr-sr-x 7 vagrant vagrant  4096 May 13 13:47 ../
drwxrwxrw- 1 vagrant vagrant  4096 May 26 18:39 .git/
-rwxrwxr-x 1 vagrant vagrant  1367 May 26 09:42 .gitignore*
-rwxrwxr-x 1 vagrant vagrant   127 May 18 13:08 .gitmodules*
drwxrwxrw- 1 vagrant vagrant  4096 May 26 11:01 .vagrant/
-rwxrwxr-x 1 vagrant vagrant  1048 May 18 13:08 LICENSE.md*
-rwxrwxr-x 1 vagrant vagrant  4199 May 26 11:20 README.md*
-rwxrwxr-x 1 vagrant vagrant  8319 May 18 13:08 Vagrantfile*
-rwxrwxr-x 1 vagrant vagrant  2448 May 23 14:16 composer.json*
-rwxrwxr-x 1 vagrant vagrant 25671 May 23 14:16 composer.lock*
-rwxrwxr-x 1 vagrant vagrant   436 May 19 19:21 config-sample.yml*
-rwxrwxr-x 1 vagrant vagrant   409 May 26 10:42 config.yml*
-rwxrwxr-x 1 vagrant vagrant  1754 May 18 13:08 gulpfile.js*
drwxrwxrw- 1 vagrant vagrant  4096 May 26 18:35 htdocs/
drwxrwxrw- 1 vagrant vagrant  4096 May 18 13:08 nginx/
drwxrwxrw- 1 vagrant vagrant  4096 May 18 07:46 scripts/
drwxrwxrw- 1 vagrant vagrant  4096 May 18 07:46 tests/
drwxrwxrw- 1 vagrant vagrant  4096 May 26 11:01 vendor/
```

What and where are these permissions set anyway? On the host computer the actual file permissions are fine and not like above.

**Comment by onnimonni** [comment]
This happens Because we are using virtualbox for mounting the files. This is a problem which is widely noticed in vagrant community. It can be fixed by using nfs-share instead but I did quick comparisons and nfs lacks speed and changes to files isn't as snappy.

Comment here if this is causing real problems

**Comment by ottok** [comment]
If this is an upstream problem, please put the url here so that upstream can be tracked.

**Comment by anttiviljami** [comment]
https://github.com/mitchellh/vagrant/issues/897 seems to be relevant here

**Comment by ottok** [comment]
This still applies. Running `chmod 755` inside Vagrant has no effect. The issue is caused by VirtualBox shares and should go away in newer VirtualBox versions.

**Comment by ottok** [comment]
This is still happening on Vagrant 2.04 and Virtualbox 5.2.18.

![image](https://user-images.githubusercontent.com/668724/53626284-fb4ed600-3c0d-11e9-8454-b17de77207dd.png)
