### ISSUE TITLE
Connecting to a development environment via SSH spits out Ruby Gem notifications

### ISSUE THREAD

**Issue by sjaks** [Seravo/wordpress#144]
On running `vagrant ssh` to connect to my development environment, I get the following notifications.
```
$ vagrant ssh
NOTE: Gem::Specification.default_specifications_dir is deprecated; use Gem.default_specifications_dir instead. It will be removed on or after 2020-02-01.
Gem::Specification.default_specifications_dir called from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/bundler.rb:428.
NOTE: Gem::Specification.default_specifications_dir is deprecated; use Gem.default_specifications_dir instead. It will be removed on or after 2020-02-01.
Gem::Specification.default_specifications_dir called from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/bundler.rb:428.
/usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/errors.rb:103: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/share/rubygems-integration/all/gems/i18n-1.8.2/lib/i18n.rb:195: warning: The called method `t' is defined here
Connecting to development environment... (ssh -- )
SSH connection confirmed
```

There seems to be some deprecated functionality in place. These do not interfere usage but are of annoyance.

Running Ubuntu 20.04 LTS, VirtualBox version 6.1.x and Vagrant 2.2.6. Ruby version is 2.7.0p0.

**Comment by sjaks** [comment]
Seems like I am getting this error also, at least, when running `vagrant up`.

**Comment by ottok** [comment]
Please report what system you have, including at least Vagrant and Ruby
versions

ma 8. kesäk. 2020 klo 15.41 Sami Jakonen <notifications@github.com>
kirjoitti:

**Comment by JoosuaKoskinen** [comment]
Looks like Vagrant was installed from distribution repository and/or used system Ruby instead of the one bundled with Vagrant. New Vagrant documentation coming to https://seravo.com/docs warns about this and Vagrant 2.2.6 isn't one of our supported versions any more.

Will close soon unless this still affects someone.

**Comment by sjaks** [comment]
I think you can close this :)
