### ISSUE TITLE
Vagrant failed to initialize at a very early stage:

### ISSUE THREAD

**Issue by Yuve1302** [Seravo/wordpress#146]
Good evening,
am using vagrant 2.2.9 version and getting an following error message when running the vagrant.

Vagrant failed to initialize at a very early stage:

The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: 2

  Minimum required version: 3

**Comment by ottok** [comment]
Did you upgrade your PowerShell version as the error message suggests?

**Comment by Yuve1302** [comment]
how can i upgrade powershell. please guide me

**Comment by ottok** [comment]
PowerShell is part of Windowds. Please see Microsoft's documentation on how
their updates work. I am not a Windows user myself, I don't know by heart
how it works unfortunately.

**Comment by ottok** [comment]
Closing this as "won't fix" as the original reporter did not confirm if updating PowerShell fixed it or not, and since nobody else has reported this either.
