### ISSUE TITLE
Requested URL returned error:404 not found

### ISSUE THREAD

**Issue by Yuve1302** [Seravo/wordpress#147]
hi, i am using winodws 7 os and i getting an error while downloading the remote file from the url https://vagrantcloud.com/puphpet/boxes/ubuntu1604-x64/version/20161102/providers/virtualbox.box.. please give an idea to slove this error  as soon as possible

**Comment by ottok** [comment]
Hello!

Issues regarding the download of phupetbox seem unrelated to the
Seravo/WordPress box.

**Comment by ottok** [comment]
Closing as invalid.
