### ISSUE TITLE
We shouldn't use accents and special characters in uploads

### ISSUE THREAD

**Issue by onnimonni** [Seravo/wordpress#16]
I think something like this should be a must-use plugin in this project: https://wordpress.org/plugins/file-renaming-on-upload/

I had lot's of trouble when one client had thousands of files in upload folder and many of them had finnish letters 'ä' and 'ö' in them. Nginx showed them correctly in vagrant but not in production.

**Comment by ottok** [comment]
Hmm.. I don't think it is worth the effort of having one more must use -plugin. If WordPress core fixes this then we'll have it, otherwise not.
