### ISSUE TITLE
RawFile#0 failed to create the raw output file /home/petri/seravo/wp-palvelu-vagrant/ubuntu-bionic-18.04-cloudimg-console.log (VERR_FILE_NOT_FOUND)

### ISSUE THREAD

**Issue by ottok** [Seravo/wordpress#166]
With box 'seravo/wordpress' (v20201205.0.0) running `vagrant up` yielded:

```
...
==> seravocom-box: Running 'pre-boot' VM customizations...
==> seravocom-box: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "be948521-2eae-45ab-b686-7b518348bf2f", "--type", "headless"]

Stderr: VBoxManage: error: RawFile#0 failed to create the raw output file /home/petri/seravo/wp-palvelu-vagrant/ubuntu-bionic-18.04-cloudimg-console.log (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
```

VirtualBox shows:

Result Code: | NS_ERROR_FAILURE (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

The problem does not manifest when using the Vagrant box seravo/wordpress-beta

**Comment by marttihyvonen** [comment]
I have a same issue, thanks for investigating this :)

**Comment by elguitar** [comment]
^ Accidental close. That SHOULD work though

**Comment by marttihyvonen** [comment]
I also got this fixed, when I disabled serial port in VirtualBox configuration as advised in here: https://github.com/joelhandwell/ubuntu_vagrant_boxes/issues/1

**Comment by elguitar** [comment]
Thank you for reporting @marttihyvonen!

The connected serial port is indeed the problem at hand.

**Comment by elguitar** [comment]
Could you test with the [new wordpress-beta box (v20210114.0.0)](https://app.vagrantup.com/seravo/boxes/wordpress-beta/versions/20210114.0.0)?

With the new box, the serial connection disconnecting should not be needed anymore.

**Comment by ottok** [comment]
Latest wordpress-beta works on the machine where I was able to reproduce the original error, so I deem this as fixed now.

**Comment by dubbajones** [comment]
VM works now. Thank you!

**Comment by elguitar** [comment]
This is fixed now, and there has been no reports of users who use the faulty box. Closing.
