### ISSUE TITLE
Enable MongoDB extension for PHP (Enhancement)

### ISSUE THREAD

**Issue by joonamakinen** [Seravo/wordpress#184]
Made a migration script that mix and matches MySQL queries with MongoDB queries for pre-formatting and utilizing bazillions of rows. Even though the final end product is purely MySQL that could potentially be migrated, the relationships with JOIN and whatnot are not my forte. I'd like to just run the same PHP endpoint with `mongodb.so` on. 

This would probably benefit other WordPress sites with complementary Node applications running.

Could this perhaps be part of upcoming PHP 8.1 build at Seravo? I'll approach my current problem differently for now.

https://docs.mongodb.com/drivers/php/

**Comment by trajche** [comment]
+1 on this. We have a plugin that does archiving to MongoDB and we are unable to use it on Seravo for now.

**Comment by ypcs** [comment]
Hi, thanks for the feedback. For the record we're considering adding support for this module. We will first execute some performance testing etc.

Like previously, if we decide to enable this module, we will add it only for the latest PHP version, which would be PHP8.1 like @joonamakinen already suggested. Release for PHP8.1 is scheduled for November 2021, so *if* our internal tests succeed and we decide to add this module, it will be available in November, at earliest.

**Comment by joonamakinen** [comment]
Even when enabling PHP 8.1 from nginx configs, composer (php-cli) won't run PHP 8.1 with ext-mongodb enabled. MongoDB requires both the extension and module `mongodb/mongodb` to be loaded. 

[https://packagist.org/packages/mongodb/](https://packagist.org/packages/mongodb/)

```bash
cd data/wordpress
composer require mongodb/mongodb
...
Package mongodb/mongodb has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - mongodb/mongodb 1.12.0 requires ext-mongodb ^1.13.0 but it is not present.   
```

![image](https://user-images.githubusercontent.com/72403821/165556740-e3f5d105-5125-4dd3-9a9e-e485bc7cebc2.png)

**Comment by ypcs** [comment]
Hi, sorry for delay in response. This feature is slowly rolling out to all customers, if there is specific sites that need feature now, please contact our customer support (help@seravo.com), we can push this to specific sites faster if needed. :)

**Comment by joonamakinen** [comment]
Since a module list of PHP 8.1 lists `mongodb` on my other issue I think this can also be closed now @ypcs 

[https://github.com/Seravo/wordpress/issues/199](https://github.com/Seravo/wordpress/issues/199)
