### ISSUE TITLE
Local development Vagrant box does not start if PHP 8.0 is in use

### ISSUE THREAD

**Issue by lecklin** [Seravo/wordpress#192]
For a new site running PHP 8.0 by default, the local dev environment `vagrant up` just wouldn't work. It usually ended up in a message stating that it is waiting for the environment to start on host X, although sometimes it did actually also output an error along the lines of `...seravo/bootstrap.d/6200-install-languages.sh exited with return code 1`.

After some digging I found the following:

`PHP Fatal error: Declaration of WP_CLI\LanguagePackUpgrader....`

Which lead me to this conversation: https://github.com/wp-cli/wp-cli/issues/5494

After I switched the site to use PHP 7.4, the local environment started up just fine. After this I noticed that `wp cli version` on production returns `2.6.0` while on the local development environment you get `2.4.0`.
As can be seen in the link above, it seems like the issue with PHP 8.0 has been fixed in WP-CLI version `2.5.0`.

Seems like it's fairly clear that the Vagrant box needs a newer version of WP-CLI, especially if new sites are now PHP 8.0 by default?

As additional information, I am running the latest beta box `v20210317.0.0`.

**Comment by ypcs** [comment]
Hi. Thanks for the feedback, and sorry for the inconvenience. We'll fix this ASAP.

**Comment by JoosuaKoskinen** [comment]
Closing as this was fixed a while back in [20220221](https://app.vagrantup.com/seravo/boxes/wordpress/versions/20220221.0.0).
