### ISSUE TITLE
Test user needs a better name than Rspec Testbot

### ISSUE THREAD

**Issue by anttiviljami** [Seravo/wordpress#20]

**Comment by ottok** [comment]
Current names defined in wp.rb line 95->. Username is 'testbotuser' and first/last is 'Test WP-palvelu'.

in swd container.yml it is defined that username is 'seravo' and first/last is 'Seravo Ylläpito'.

These two usernames should be aligned and self-explanatory.

Suggestion:
- seravo-admin "Seravo Maintenance User"
- seravo-test "Seravo Test User"

Bot should have as email no-reply@seravo

**Comment by ottok** [comment]
To stress this: the account e-mail addresses should always be no-reply@seravo dot fi and never anything like testbotuser@wp-siteurl.com

**Comment by ottok** [comment]
As per https://github.com/Seravo/wordpress/commit/c514066f4fa26c2d701047f7fe6f36c4bfa74734 and the dash in username limit, let's call the users instead:

* seravo "Seravo Admin User"
* seravotest "Seravo Test User"

Both should have as email no-reply@seravo

**Comment by anttiviljami** [comment]
You can't have two users with the same email. Seravo Admin User should use wordpress@seravo.fi while the test user should use no-reply@seravo.fi

**Comment by ottok** [comment]
No, no machine account should have the address of customer service. Make seravo have no-reply@ and seravotest have noreply@ (without dash).

**Comment by anttiviljami** [comment]
The user seravo "Seravo Admin User" is not a machine account. It's the one we use to manually log in to the user's website. I think it should definitely have the correct customer service email account
