### ISSUE TITLE
Object cache drop-in not compatible with PHP 8.1

### ISSUE THREAD

**Issue by villeveikkoilen** [Seravo/wordpress#204]
[Object cache drop-in file](https://github.com/Seravo/wordpress/blob/e67cab59bc6690738531bedf219d29a3979d0b8b/htdocs/wp-content/object-cache.php)

When using PHP 8.1, the drop-in causes the following errors in Vagrant development environment:
```
Deprecated: strcasecmp(): Passing null to parameter #2 ($string2) of type string is deprecated in /data/wordpress/htdocs/wp-content/object-cache.php on line 436
Deprecated: Redis::connect(): Passing null to parameter #5 of type int is deprecated in /data/wordpress/htdocs/wp-content/object-cache.php on line 512
```

WP: 6.2.2
Vagrant box version: 20220808.0.0

**Comment by ypcs** [comment]
Thanks for opening the issue. Unfortunately there was no previously any message when this was resolved in https://github.com/Seravo/wordpress/pull/205 . So, projects using new project template should have recent enough version of the object-cache plugin.
