### ISSUE TITLE
Vagrant box static IP doesn't work if it ends in ".1"

### ISSUE THREAD

**Issue by tnottu** [Seravo/wordpress#29]
The vagrantfile generates a `private.ip` file on install, with a random static IP address. I just happened to get an IP which ended in `.1` and on boot Vagrant warns in the console:

```
==> wordpress-box: You assigned a static IP ending in ".1" to this machine.
==> wordpress-box: This is very often used by the router and can cause the
==> wordpress-box: network to not work properly. If the network doesn't work
==> wordpress-box: properly, try changing this IP.
```

Indeed, I couldn't connect to the WP install from the browser. Deleting the `private.ip` file and rebooting the box fixed the problem.

This is an edge case really, but perhaps the random IP generator should make a reroll if the IP ends `.1`?

**Comment by anttiviljami** [comment]
Nice catch! We might also want to disallow ips ending with `.0`. 

Wanna help us fix this in the Vagrantfile?
