### ISSUE TITLE
PHP7 by default?

### ISSUE THREAD

**Issue by anttiviljami** [Seravo/wordpress#33]
Should we enable php7 by default in this repo configuration? This would take effect for both vagrant and wp-palvelu environments.

I feel like php7 is starting to be stable enough to be the default for all *new* projects. 

The user can always fall back easily to 5.6, or just use HHVM if they wish using our nginx custom.conf.

https://docs.wp-palvelu.fi/configuration/php7-hhvm/

**Comment by ottok** [comment]
Yes please! 😂

19.7.2016 1.11 ip. "Antti Kuosmanen" <notifications@github.com> kirjoitti:

**Comment by lehtu** [comment]
How about the situation with plugins and themes? Not sure how many of those are ready for this change :/

**Comment by anttiviljami** [comment]
According to my testing for a couple of months now with tens of sites and researching the php7 changes, I would say the vast majority of themes and plugins are readily compatible. There aren't really drastic changes in the php7 syntax.

http://php.net/manual/en/migration70.incompatible.php

**Comment by anttiviljami** [comment]
And even if they aren't, you can just change one line in the nginx custom.conf file to use 5.6 again. :)

**Comment by ottok** [comment]
Making PHP 7 default in this repo would only affect new sites, so it is pretty safe to do in relation to the likelyhood and seriousness of potential regressions. So just do it ;)
