### ISSUE TITLE
Mail not being sent

### ISSUE THREAD

**Issue by spktklr** [Seravo/wordpress#34]
Getting "your host may have disabled the mail() function" error on retrieving a lost password (
https://wordpress.local/wp-login.php?action=lostpassword). No other mail is being sent either - mailcatcher is empty. Also occurs on a vanilla install, following installation instructions on https://github.com/Seravo/wp-palvelu-vagrant.

Just a hunch but might be related to .dev -> .local switch

**Comment by anttiviljami** [comment]
Seems to me this is probably an issue with the https://github.com/Seravo/wp-palvelu-vagrant image. Looking into it

**Comment by anttiviljami** [comment]
This is fixed in: https://github.com/Seravo/wp-palvelu-vagrant/commit/b1a6bbd71a57711ea6a83d615d735fbdf76a3526

**Comment by anttiviljami** [comment]
Vagrant image will be up soon :)
