### ISSUE TITLE
Version 2.x of phpdotenv

### ISSUE THREAD

**Issue by anttiviljami** [Seravo/wordpress#36]
We're currently using version 1.0.9 of phpdotenv. The new version has apparently changed its API slightly.

The trouble with this is that because composer libs are global, and some plugins using the composer autoloader might want to use a different version of dotenv, which wont work between 1.x and 2.x. 

We should maybe start supporting the 2.x version of phpdotenv, if it turns out lots of plugins are using the newest version.

**Comment by ottok** [comment]
:+1:
