### ISSUE TITLE
Git pre commit hook should test only the committed files and not all of head

### ISSUE THREAD

**Issue by onnimonni** [Seravo/wordpress#4]
When I run ```git commit file.php -m "message"``` the pre-commit hook tests the state containing all latest files in directory.  It should only test head + files_to_be_committed so there won't be any mismatch with the tests and commits.

**Comment by anttiviljami** [comment]
One solution would be that we do a trial commit where clean up everything before the actual commit:

e.g.

```
git commit -n "pre-commit temporary commit" # create a test commit 
git stash # gets rid of all unstaged changes
{run tests} 
git reset HEAD~1 # drop the temporary commit
git stash apply # pull back unstaged changes 
```

I'm just not sure if committing inside a pre-commit script is even possible.

**Comment by onnimonni** [comment]
Well we can use The git commit -n flag so ofc it is possible. This just seems really hacky :O



--
Onni Hakala
0445158280
onni@koodimonni.fi
Koodimonni TMI
