### ISSUE TITLE
Prompt to use object cache instead of turning it on by default

### ISSUE THREAD

**Issue by k1sul1** [Seravo/wordpress#42]
Story: I started a new project on friday, and today when I came to work, Vagrant wouldn't start normally. I ran `vagrant destroy` followed by a `vagrant up` and got it back up and running. For whatever reason, I didn't have a shutdown dump, so I was presented with the default display of Twenty Sixteen. Luckily I store additional backups of the development database, so I restored last known good backup: 

`wp db reset`
`wp db import local_database_backups/1480886101.sql`

This didn't seem to work, I was still stuck looking at the default theme and of my data was "missing", so I ran `wp db reset` again to nuke the database, and to my surprise, /wp-admin continued working normally. 

I went to confirm that the database is indeed empty: 
```
vagrant@wordpress:~$ wp db cli
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 124
Server version: 10.1.19-MariaDB-1~trusty mariadb.org binary distribution

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [vagrant]> show tables;
Empty set (0.00 sec)

MariaDB [vagrant]> Ctrl-C -- exit!
```

I finally figured out that this was happening due to object cache, and after running `sudo service redis-server restart` I was presented with the lovely "install WordPress" screen and I was able to successfully import the backup database and get back to work. 

I as an user didn't know that I was using object cache, because it wasn't on by default last time. This should be made more clear to the user, and clearing the object cache should be easier. It's fairly easy in production but on development not so much. 

Suggestion:  add an additional prompt to first `vagrant up`, asking if the user would like to enable object cache, and add a wp-purge-cache command to the local environment. That would allow users to easily get rid of any remnants left by a previous installation.

**Comment by anttiviljami** [comment]
I totally agree. 

The redis cache can cause slowdowns and even issues on some sites. It's too dangerous to have on by default, which we've discussed in detail in the past many times. 

Reverting the last commit by @ottok which made the redis cache be enabled by default.

**Comment by ottok** [comment]
We haven't seen any negative effects with using object-cache.php and Redis despite having it on by default for a long time. In development it is automatically of just like all other caching. So I am closing this issue as not relevant anymore.
