### ISSUE TITLE
Custom provisioning script

### ISSUE THREAD

**Issue by k1sul1** [Seravo/wordpress#44]
Currently it seems that there's no way to run custom provisioning scripts (adding features such as local backups, maybe changing some settings etc) without modifying Vagrantfile directly. 

I'm proposing a new feature to the Vagrantfile: check if a custom provisioning script (`customize_vagrant.sh`?) exists in the directory, and if it does, run it. 

It should be fairly straightforward, add a few lines, including something like this 
`config.vm.provision "shell", path: "customize_vagrant.sh"`
[to this block of code](https://github.com/Seravo/wordpress/blob/a68202576de8e1d6b5bf757b6513af033996ab8e/Vagrantfile#L232).

**Comment by anttiviljami** [comment]
I like this idea. :+1:

**Comment by ottok** [comment]
Yes, good idea. Actually I know at least one use case already where this would solve a customer issue. Do you @k1sul1 happen to know any existing examples where this pattern is already used, so we could check what naming schemes to follow and any potential caveats etc?

**Comment by k1sul1** [comment]
Can't think of any. I've never used VVV so can't say anything about it, and roots/trellis is a _bit_ more  complex than this. 

Maybe the implementation could be similar to this? https://github.com/Seravo/wordpress/tree/master/nginx

**Comment by ottok** [comment]
@k1sul1 What is it you want to customize in your script? VirtualBox settings? Make custom search-replace to the database? Give some examples so I know what use case this should server.

**Comment by ottok** [comment]
@k1sul1 Implemented now ae51719e146615e7fcbde6b69c8a1deeb386510e - is this usable for your needs?

**Comment by k1sul1** [comment]
Should be. 

My current use: I create a script that takes local database backups and runs every n minutes using cron, because Vagrant has proven itself to be quite volatile and no one remembers to take backups manually.

**Comment by ottok** [comment]
No further discussion, closing issue as ae51719 seems to have fixed this.
