### ISSUE TITLE
Hide Seravo test user on front-end of customers website 

### ISSUE THREAD

**Issue by runomarsista** [Seravo/wordpress#46]
Don't list Seravo test user on front-end of customers website. Some customers may have page which shows all WordPress users.

**Comment by ottok** [comment]
The user is created in https://github.com/Seravo/wordpress/blob/master/tests/rspec/lib/wp.rb#L94-L120
We decided originally not to delete the customer after each test run to avoid unnecessarily incrementing the user id on every test run.

Maybe the best solution would be to add some kind of user listing filter, that would remove the Seravo test user from user lists? One idea would be to hook into the [pre_get_users](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/class-wp-user-query.php#L237) action and always force the `$exclude` variable to contain the user id of the Seravo test user.
