### ISSUE TITLE
Trusting self-signed cert command fails on macOS if there are spaces in the filepath

### ISSUE THREAD

**Issue by danielck** [Seravo/wordpress#50]
Spaces in the `ssl_cert_path` variable are not escaped when passed to the `sudo security add-trusted-cert ...` command in Vagrantfile on line 175. As a result the command fails.

Whether it's a good idea to have spaces in directory names is another discussion, but this should be simple to fix: escape spaces with a backslash, e.g. `/Local Sites` --> `/Local\ Sites`

**Comment by l3ku** [comment]
Development in progress at https://github.com/Seravo/wordpress/tree/fix-osx-add-trusted-cert.
