### ISSUE TITLE
Disable WordPress comments and user registration by default

### ISSUE THREAD

**Issue by runomarsista** [Seravo/wordpress#52]
Disable WordPress comments and user registration by default

**Comment by ottok** [comment]
@runomarsista Find out what the option name is and add a stanze next to these: https://github.com/Seravo/wordpress/blob/master/htdocs/wp-content/install.php#L122-L127

**Comment by runomarsista** [comment]
Reinvestigated issue and noticed that both features are already disabled by default on Seravo WordPress

**Comment by runomarsista** [comment]
Reinvestigated issue and noticed that both features are already disabled by default on Seravo WordPress
