### ISSUE TITLE
wp-use-asset-proxy sometimes fails

### ISSUE THREAD

**Issue by k1sul1** [Seravo/wordpress#56]
For whatever reason, the asset proxy doesn't always work, and I end up with 404s on my local setup. I suspect it might have something to do with relative urls, because this fails to load: 

`<img src="/wp-content/uploads/2017/03/shutterstock-515359459@3x-1-768x776.jpg">`

That image is coming from an ACF image field with a return type set to object, and it only has root relative urls in it. Assuming the issue is caused by relative urls, any status on #47? Can we disable them on existing installs without breaking everything? 

To work around this issue, I simply synced those missing media files using rsync. I was sure that there used to be a `wp-pull-production-assets` installed on the Vagrant box, but apparently no such thing exists.

**Comment by ottok** [comment]
Asset proxy works via localhost/Vagrant, and relative urls should not make them fail. To understand your scenario, please give more information: Which is the full URL that fails? What is the site URL which the image should be using? What does your browser complain? Screenshot from browser with dev console open?

**Comment by k1sul1** [comment]
I've not been able to reproduce this in a while. Guess it is safe to close this issue.
