### ISSUE TITLE
Vagrant halt, vagrant up reseted db on local test environment for mac

### ISSUE THREAD

**Issue by tlehtimaki** [Seravo/wordpress#58]
I've had a problem where database was reset when vagrant machine went down and I run vagrant up again. What could be causing this?

**Comment by tlehtimaki** [comment]
Found out that in folder `.vagrant/machines/` there was more than one machine. This is probably a result from editing the config once vagrant box was running. Thus running `vagrant up` on console caused a new machine to be created.

**Comment by ottok** [comment]
Tip: `vagrant global-status`

**Comment by tlehtimaki** [comment]
Thanks! Thats a good tip. Never used that command before. Perhaps good "nice to know" tip for the docs too. 👍
