### ISSUE TITLE
Default install still installs lots of plugins

### ISSUE THREAD

**Issue by danielck** [Seravo/wordpress#6]
Composer.lock is not up-to-date with the changes made to composer.json, resulting in lots of plugins being installed. Probably composer.lock shouldn't be in the repo at all?

**Comment by onnimonni** [comment]
We reduced lot's of plugins and updated .lock file. Maybe we should put it into gitignore but I'm not sure. I have to think about it, thanks for feedback

**Comment by anttiviljami** [comment]
We no longer install a million plugins. :)
