### ISSUE TITLE
Run e2e tests in pre-push hook by default

### ISSUE THREAD

**Issue by k1sul1** [Seravo/wordpress#61]
Let's face it. The rspec tests are slow, and doing subsequent commits one after another and forgetting to skip them is a bit painful, especially because we can't abort the tests. ^C or ^D will stop the `git commit`, but the tests will keep running in the background and flood stdout with the test output. 

Wouldn't running them in `pre-push` make more sense? Syntax error checks and other _quick_ operations could still be ran in `pre-commit`, but I personally move everything into `pre-push`, because I can always alter the history until I push my changes.

**Comment by ottok** [comment]
We have been offering both https://github.com/Seravo/wordpress/blob/master/scripts/git-hooks/pre-commit and a smaller https://github.com/Seravo/wordpress/blob/master/scripts/git-hooks/pre-commit-minimum for a long time. The test itself runs with `wp-test --fail-fast` to stop quickly if there are issues. All of these help to save time.

Installation of the pre-commit hook is not forced, developers do it themselves. They can also opt to install it as pre-push.

With these measures I will close this issue now, as developers are much less likely to have issues with this now in 2021 anymore.
