### ISSUE TITLE
Deny access to non-entry-point PHP files

### ISSUE THREAD

**Issue by szepeviktor** [Seravo/wordpress#63]
Please consider translate it from Apache conf. It is straightforward.
https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/apache-conf-available/wordpress.inc.conf

Note: You have to add exceptions for poorly written themes and plugins which open new entry-points.

**Comment by ottok** [comment]
We should first scan our access logs and make sure there are no legitimate direct use of PHP files in the `plugins` or `themes` folders.

We would also like to deny storing or using PHP files in the `uploads` folder, but we've noticed that there actually are legit use cases, so we can't do it unless all major plugin authors start to agree to store the files their plugins write in other locations.

**Comment by szepeviktor** [comment]
> legitimate direct use of PHP files

WordPress has enough entry points: https://github.com/szepeviktor/WPHW/blob/master/wp-entry-points.md

Only poorly written plugins - with authors speaking only PHP - create custom ones.

I think it worth blocking poorly written plugins, projects a bright future.

**Comment by ottok** [comment]
We have always been blocking many entrypoints (for example all files and directories that start with a dot, e.g. `.git`). We have extended the blocks over the years based on what feels safe and do not hamper with normal operations of our customers WordPress sites.

Work continues to fine tune blocking lists in an internal issue.

Thanks for the tips!

**Comment by szepeviktor** [comment]
One day @Servao may hire me...
