### ISSUE TITLE
Support drop-ins for this repository

### ISSUE THREAD

**Issue by k1sul1** [Seravo/wordpress#67]
Using a drop-in Composer package seems to be the most convenient way of customizing Vagrant and the files in this repository. See [Vincit/wordpress](1) and  [kehittamo/kehittamo-seravo-addons](2) for examples. 

However, that currently requires manual modification of composer.json. 
```
"dropin-paths": {
      "htdocs/wp-content/languages/": ["vendor:koodimonni-language"],
      "htdocs/wp-content/languages/plugins/": ["vendor:koodimonni-plugin-language"],
      "htdocs/wp-content/languages/themes/": ["vendor:koodimonni-theme-language"]
  },
```

=>

```
"dropin-paths": {
      "htdocs/wp-content/languages/": ["vendor:koodimonni-language"],
      "htdocs/wp-content/languages/plugins/": ["vendor:koodimonni-plugin-language"],
      "htdocs/wp-content/languages/themes/": ["vendor:koodimonni-theme-language"],
      ".": ["type:seravo-wordpress-dropin"]
  },
```
Then we can just clone this repository and run `composer require vendor/customizations --dev` to include our customizations. The package type is simply "seravo-wordpress-dropin". 

#62 is related to this in a way. 

I'll gladly send a PR (:grin:) but I think you might have something to say on the name part. So what should we call "seravo-wordpress-dropin"?

**Comment by ottok** [comment]
seravo-wordpress-dropin sounds good, please send a PR for review

I hope the invitation to our office party reached you. Thanks a lot for your contributions!

**Comment by ottok** [comment]
Links of the repos above:
* https://github.com/kehittamo/kehittamo-seravo-addons
* https://github.com/Vincit/wordpress

**Comment by k1sul1** [comment]
It did. I haven't responded to the invitation yet, as I don't know what my calender looks like. I'll know better tomorrow afternoon.
