### ISSUE TITLE
http://localhost is hard-coded in test.rb

### ISSUE THREAD

**Issue by danielck** [Seravo/wordpress#7]
After setting a custom url in config.yml and doing a git commit, the tests fail, even though the command line output suggests that the tests are being run with the correct url. The culprit seems to be on lines 90 and 108 of test.rb:

On line 90:
`visit 'http://localhost/'`

On line 108:
`visit "http://localhost/wp-login.php"`

**Comment by onnimonni** [comment]
Yeah, it was only meant for temporary usage anyways. This was fixed in a581e5d4467ad5bff932353e03aa12a2ad36ec9c
