### ISSUE TITLE
502 bad gateway when trying to start a WP All Import Pro import

### ISSUE THREAD

**Issue by k1sul1** [Seravo/wordpress#77]
Every time I try to import new items from https://wordpress.org/news/feed to posts using WP All Import Pro, I get a 502. 

It also seems to crash php7-fpm, because this happens on other pages immediately after. 
![image](https://user-images.githubusercontent.com/2719615/34518634-daf1de74-f088-11e7-8c87-19c26ac80c06.png)

Running `wp-restart-php7-fpm` makes the syntax error go away, but the bad gateway remains.

**Comment by k1sul1** [comment]
[wpaip.zip](https://github.com/Seravo/wordpress/files/1600151/wpaip.zip)

Here's a copy of the plugin.

**Comment by k1sul1** [comment]
Turns out this happens on other instances (not Seravo) also, so it isn't related to this. 

The syntax error is a weird one though. It's almost as if it tries to use PHP5 if php7-fpm crashes.

**Comment by ottok** [comment]
Yes, if PHP 7 fails it will on the fly fall-back to PHP 5.6. This was designed to handle code that is PHP 7.x incompatible.

**Comment by ottok** [comment]
Did you try fixing the syntax error, the double ?? in the theme code you have in the screenshot above?

**Comment by k1sul1** [comment]
The "syntax error" is PHP 7 spesific code, it's expected that it doesn't run on PHP 5. 

It's possible that our version of the plugin is corrupted/outdated in Packagist.com.

**Comment by k1sul1** [comment]
Since this is probably going to appear on Google search, might as well share the solution.

https://stackoverflow.com/questions/23844761/upstream-sent-too-big-header-while-reading-response-header-from-upstream/23845727#23845727
