### ISSUE TITLE
Rspec tests are failing if Jetpack additional login module is enabled

### ISSUE THREAD

**Issue by runomarsista** [Seravo/wordpress#78]
Rspec tests are failing if Jetpack additional login module is enabled. Module allows user to login with wordpress.com account and test needs more logic.

**Comment by ottok** [comment]
Rspec was removed in 4e82a3bd7944c4a4a3b7ffa67a9a54d510076c6d and our new Codeception based test system is able to log in past various custom logins, including Jetpack, so this issue can now be closed.
