### ISSUE TITLE
Travis CI tests randomly fail loading statics assets

### ISSUE THREAD

**Issue by ottok** [Seravo/wordpress#79]
In some Travis CI runs the log has lines like:
```
An error occurred in an `after(:context)` hook.
  Capybara::Poltergeist::StatusFailError: Request to 'http://localhost:12000/' failed to reach server, check DNS and/or server status - Timed out with the following resources still waiting http://localhost:12000/wp-content/themes/twentyseventeen/assets/js/jquery.scrollTo.js?ver=2.1.2
  occurred at /home/travis/.rvm/gems/ruby-2.2.5/gems/poltergeist-1.10.0/lib/capybara/poltergeist/browser.rb:365:in `command'
[Mon Feb  5 20:23:45 2018] 127.0.0.1:35192 Invalid request (Unexpected EOF)
```

This is related to bugs:
* https://bugs.php.net/bug.php?id=60471
* https://github.com/ariya/phantomjs/issues/10652
* https://stackoverflow.com/questions/29141240/php-local-server-invalid-request-unexpected-eof

This is mostly a PHP bug, because the same PhantomJS version works reliably when running PHP 5.6 server but not when running PHP 7.0 or newer server. It might also be bug in our [router.php](https://raw.githubusercontent.com/Seravo/wordpress-test-template/master/lib/router.php) that maybe isn't optimized for PHP 7?

**Comment by l3ku** [comment]
If this problem is still present, it will be eliminated when we deprecate `router.php` and use our CI Docker image for testing instead.

**Comment by ottok** [comment]
We are no longer using PhantomJS since 27fbef19af9ba8abb016bf68cb45fd46e8a55f03, so this issue can be closed now.
