### ISSUE TITLE
Move WPML cache outside wp-content/uploads

### ISSUE THREAD

**Issue by ypcs** [Seravo/wordpress#82]
By default WPML plugin saves it's cache files (including `* .php`) under `wp-content/uploads`. This is bad practice, PHP files should never reside below `uploads`.

However, WPML allows moving it's cache directory. This makes it possible to set default cache path in `wp-config.php`, by defining `WPML_CACHE_PATH_ROOT`.

```php
define( 'WPML_CACHE_PATH_ROOT','/data/wordpress/htdocs/wp-content/wpml-cache/');
```

This would affect anyone who starts building their site from this template. (This can be applied to existing sites too.)

During testing I also noticed, that change gets applied after admin has visited WPML settings pages.

**Comment by ottok** [comment]
:+1:

**Comment by k1sul1** [comment]
One might argue that WPML is a bad practice but anything that makes it suck less is an improvement...

**Comment by ottok** [comment]
How about `define( 'WPML_CACHE_PATH_ROOT','/data/wordpress/htdocs/wp-content/cache/wpml/')`; ?
With this design pattern we can optimize for caching everything at root path `wp-content/cache`

**Comment by zyrup** [comment]
WMPL is still creating .php cache files inside /uploads
