### ISSUE TITLE
Latest commit (Use PHP 7.2 by default on new sites) breaks the dev environment as seravo/wordpress doesn't have PHP 7.2 installed

### ISSUE THREAD

**Issue by nakanaa** [Seravo/wordpress#83]
The subject says it all, but in short right now running `git clone git@github.com:Seravo/wordpress.git` and then `vagrant up` gives you a broken dev environment where nginx tries to use PHP 7.2 but fails with `500 Internal Server Error`

Edit: Oh yeah and the box is the newest available (20170829.14.0000)
```
➜  wordpress git:(master) ✗ vagrant box list
seravo/wordpress      (virtualbox, 20170829.14.0000)
```

**Comment by ottok** [comment]
Actually we have not updated the Vagrant image yet to include PHP 7.2. 

The Vagrant box in undergoing a major refactoring and publishing the next version will take some time. We are for example waiting for upstream to accept our Vagrant plugin patches :)

I will revert that change as it is incompatible with current Vagrant box.
