### ISSUE TITLE
Vagrant box could not be found (migrated atlas.hashicorp.com -> vagrantcloud.com in Jan 2018)

### ISSUE THREAD

**Issue by k1sul1** [Seravo/wordpress#84]
People coming in to a project are reporting that Vagrant doesn't work, it fails in initial `vagrant up`, with this output:

```
Bringing machine 'redacted-box' up with 'virtualbox' provider...
==> redacted-box: Box 'seravo/wordpress' could not be found. Attempting to find and install...
    redacted-box: Box Provider: virtualbox
    redacted-box: Box Version: >= 20160718.15.0122
The box 'seravo/wordpress' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/seravo/wordpress"]
Error: The requested URL returned error: 404 Not Found
```

**Comment by ottok** [comment]
Yes, the image is still there: https://app.vagrantup.com/seravo/boxes/wordpress
However Vagrant needs an update.

The problem is that Hashicorp Atlas has seized to exist – All of https://atlas.hashicorp.com just redirects to a new Terraform sign up page.

If you try to start Vagrant using an image that has nothing to do with Seravo, you get the same error message:
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/xenial64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'ubuntu/xenial64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/xenial64"]
Error: The requested URL returned error: 404 Not Found
```

**Comment by k1sul1** [comment]
Apparently it started working after a Vagrant update.

**Comment by ottok** [comment]
You also need to make sure your existing images metadata is updated. See the files you have with `find ~/.vagrant.d/boxes/*/metadata_url`and edit them to use `vagrantcloud.com` like this:
```
cat ~/.vagrant.d/boxes/seravo-VAGRANTSLASH-wordpress/metadata_url
https://vagrantcloud.com/seravo/wordpress
```

**Comment by ottok** [comment]
People are unlikely to bump into this anymore, so no need to keep this open for informational purposes. The issue itself is fixed and most likely all project templates that had this have been updated by their respective developers.
