### ISSUE TITLE
Migrate vagrant-triggers to Vagrant core triggers

### ISSUE THREAD

**Issue by nakanaa** [Seravo/wordpress#88]
Vagrant integrated the functionality of vagrant-triggers plugin to the core with version 2.1.0:
https://github.com/hashicorp/vagrant/blob/master/CHANGELOG.md#210-may-3-2018

After updating Vagrant and running`vagrant up` you now get (by default):
```
WARNING: Vagrant has detected the `vagrant-triggers` plugin. This plugin conflicts
with the internal triggers implementation. Please uninstall the `vagrant-triggers`
plugin and run the command again if you wish to use the core trigger feature. To
uninstall the plugin, run the command shown below:

  vagrant plugin uninstall vagrant-triggers

Note that the community plugin `vagrant-triggers` and the core trigger feature
in Vagrant do not have compatible syntax.

To disable this warning, set the environment variable `VAGRANT_USE_VAGRANT_TRIGGERS`.
```

Everything still seems to work, but migrating away from the plugin should probably still be done sooner or later. VVV has done the migration and could provide a good example:
https://github.com/Varying-Vagrant-Vagrants/VVV/commit/498825a0601524d54cf12f689c07695d52ba16c7
(plus the subsequent commits)

Might look into this myself and do a pull request if I can find the time.

**Comment by ottok** [comment]
We are planning to migrate away from the plugin, but that requires non-backwards compatible changes, so we are postponing for now, as we don't want to break the workflow of existing users too much.

**Comment by ottok** [comment]
This will be fixed as part of a currently on-going refactoring of the whole Vagrant bootstrap process. In the mean time added this note to [docs](https://seravo.com/docs/development/how-to-install/): https://github.com/Seravo/docs/commit/70bb7ec79537237ccbb476d65e22587fe349a5fd

**Comment by reidelliott** [comment]
How/where do you set the environment variable `VAGRANT_USE_VAGRANT_TRIGGERS`?

**Comment by ypcs** [comment]
You can eg. just execute `export VAGRANT_USE_TRIGGERS=1` in your terminal.

**Comment by ottok** [comment]
Docs on new built-in trigger syntax: https://www.vagrantup.com/docs/triggers/configuration.html#run_remote
