### ISSUE TITLE
Issue with php7.2

### ISSUE THREAD

**Issue by luuptekman** [Seravo/wordpress#90]
There seem to be some issues with php7.2 setup. After setup I go to my local url and will end up with error 500 page.

When checking the logs, this is found:
`==> /data/log/nginx-error.log <==
2018/09/17 12:12:58 [error] 2550#0: *7 no port in upstream "php7.2", client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "myserver.local"`

If I modify examples.conf to `set $mode php7` everything is ok, site is working normally.

**Comment by ottok** [comment]
Thanks for the report! Which version of the Seravo WP Vagrant image do you have? Or if this is in production, please contact our customer support with details about the case.

You can also test our next Vagrant version in advance by replacing:
https://github.com/Seravo/wordpress/blob/master/Vagrantfile#L51-L55

With:
```
  config.vm.box = 'seravo/wordpress-beta'
```

**Comment by luuptekman** [comment]
Seems the problem was that I had too old box in use..
`You currently have version '20170829.14.0000'. The latest is version '20180605.0.4'. Run `vagrant box update` to update.`

After executing `vagrant box update` seems to work nicely.

I guess line 52 `config.vm.box_version = ">= 20160718.15.0122"` in Vagrantfile should be edited so that box will support php7.2?

**Comment by ypcs** [comment]
This was fixed 4 months ago in https://github.com/Seravo/wordpress/commit/f126182dd1430c71153da3807d37d8d70413faf2 .
