### ISSUE TITLE
Persistent database

### ISSUE THREAD

**Issue by roopemerikukka** [Seravo/wordpress#93]
I installed some updates to my computer and it required restart so I restarted my machine. After the boot the vagrant box required `vagrant up`. For my surprise the `vagrant up` also installed the whole wordpress again and I lost my whole development database.

Should this setup keep the database persistent somewhere and is there still some way to retrieve the lost data?

I have not used vagrant that much but I'm more familiar with Docker and at least with that I haven't been able to lose the database so I'm not sure if the vagrant even should work in similar way?

**Comment by ottok** [comment]
When you run `vagrant halt` or `vagrant destroy` the database is automatically saved as a SQL dump in project folder `.vagrant` even if the Vagrant virtual machine would be deleted. As long as you don't delete the Vagrant virtual box the database is stored as-is in binary format inside the Vagrant virtual machine.

How you got everything lost (including the project folder?) in a restart of your laptopt – I don't know..

**Comment by roopemerikukka** [comment]
Nope the project folder and all of the code was still in place. The virtual machine was also still in place but the `vagrant up` command just made an fresh installation of the wp and so on also new database.

I actually did not try to look inside the virtual machine but just ran the `vagrant up` command as other commands gave me an error that the machine is not running.

**Comment by spktklr** [comment]
I don't know if you've already got this sorted out, but my interpretation is that @roopemerikukka just restarted his computer without running `vagrant halt` or `vagrant destroy`, which results the virtual machine being put in an `aborted` (or similar) state. This does not dump the SQL. So the next time a `vagrant up` is performed the previous dump is imported and changes lost.

**Comment by roopemerikukka** [comment]
Yep that seems to have been the case. I thought that the vagrant would behave similarly to Docker where all of the containers are gracefully shut down when the machine shuts down. I've now installed the Vagrant manager that kind of does the same thing and thats has resolved the problem for me.
