### ISSUE TITLE
PHP 7.3 502 Bad Gateway

### ISSUE THREAD

**Issue by nturbanov** [Seravo/wordpress#95]
Running the latest version with PHP 7.3 enabled by default produces random 502 Bad Gateway errors.

Error msg in `/data/log/nginx-error.log`

`2019/02/28 12:25:09 [error] 1560#1560: *56 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /wp-admin/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "wordpress.local"
`

Restarting nginx and/or PHP doesn't seem to help. 

PHP 7.2 works fine.

This on the latest Seravo Vagrant Box version 20190122.0.0.

**Comment by ottok** [comment]
Looks like PHP crashes. Do you get any output in /data/php-error.log or any other debug.log? If you run `wp-php-compatibility-check` (in Vagrant on in production or a shadow) does it tell you that you have code that is not PHP 7.3 -compatible?

**Comment by nturbanov** [comment]
This is when running locally with a clean clone, no changes or custom code. 

`wp-php-compatibility.log`

```
E...........................................................  60 / 156 (38%)
............................................................ 120 / 156 (77%)
....................................                         156 / 156 (100%)



FILE: /data/wordpress/htdocs/wp-content/install.php
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been aborted. The error message was: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in
   |       | /usr/share/php/PHP/CodeSniffer/src/Tokenizers/Tokenizer.php on line 654
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Time: 14.68 secs; Memory: 62.01Mb
```

`nginx-error.log`

```
2019/02/28 16:42:22 [error] 1049#1049: *9 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "wordpress.local"
2019/02/28 16:46:00 [error] 1049#1049: *14 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "wordpress.local"
2019/02/28 16:48:02 [error] 1049#1049: *19 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "wordpress.local"
2019/02/28 16:48:21 [error] 1049#1049: *26 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /wp-admin/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "wordpress.local"
2019/02/28 16:48:46 [error] 1049#1049: *31 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /wp-admin/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "wordpress.local"
2019/02/28 16:48:47 [alert] 1049#1049: 768 worker_connections are not enough
2019/02/28 16:48:47 [error] 1049#1049: *1288 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: , request: "GET //favicon.ico HTTP/1.0", upstream: "http://127.0.0.1:80//favicon.ico", host: "wordpress.seravo.local"
2019/02/28 16:49:26 [error] 1048#1048: *1291 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "wordpress.local"
```

`php-error.log`

```
[28-Feb-2019 16:42:22] WARNING: [pool www] child 1042 exited on signal 11 (SIGSEGV - core dumped) after 8.755754 seconds from start
[28-Feb-2019 16:46:00] WARNING: [pool www] child 1052 exited on signal 11 (SIGSEGV - core dumped) after 217.813649 seconds from start
[28-Feb-2019 16:48:02] WARNING: [pool www] child 1080 exited on signal 11 (SIGSEGV - core dumped) after 123.068172 seconds from start
[28-Feb-2019 16:48:21] WARNING: [pool www] child 1081 exited on signal 11 (SIGSEGV - core dumped) after 141.208684 seconds from start
[28-Feb-2019 16:48:46] WARNING: [pool www] child 1084 exited on signal 11 (SIGSEGV - core dumped) after 43.929639 seconds from start
[28-Feb-2019 16:49:26] WARNING: [pool www] child 1088 exited on signal 11 (SIGSEGV - core dumped) after 64.715767 seconds from start
```

**Comment by ottok** [comment]
We have now been able to reproduce this and are working to analyze the coredumps with gdb.

**Comment by ottok** [comment]
We have now published a new version of the seravo/wordpress-beta Vagrant box with updated PHP 7.3, and the segfault is no longer present.

See https://github.com/Seravo/wordpress/commit/6fe762241aa355ac000445e4c5b66c189282e1ff if you want to test it yourself.

This fix will be soon in the official seravo/wordpress Vagrant box as well in near future.

**Comment by luuptekman** [comment]
Should this be already fixed? Cloning this repo now will end up with 502 errors.

When I run `vagrant box update`, it seems to download the new package, but it's not using.

See this output after new box has been got and `vagrant up` used:

`
==> mynewsite-box: A newer version of the box 'seravo/wordpress' for provider 'virtualbox' is
==> mynewsite-box: available! You currently have version '20190122.0.0'. The latest is version
==> mynewsite-box: '20190513.0.0'. Run vagrant box update to update.
`

Updating PHP to 7.2 in php.conf will fix the issue..

**Comment by ottok** [comment]
Did stop remove the old box first with `vagrant box destroy`? Vagrant does not use new boxes if an old is around.

**Comment by luuptekman** [comment]
Nope, thought that `vagrant box update` will update the box right away...Anyway, I have the fix now for the problem, but the root problem is clearly there still :)

**Comment by luuptekman** [comment]
This problem:

1. Clone this repo
2. Setup config.yml for the project
3. Run `vagrant up` (with the assumption that you don't have the latest box). This is what I had:
`seravo/wordpress   (virtualbox, 20190122.0.0)`
4. Go to yoursite.local ==> random 502 erros

**Comment by ottok** [comment]
Yes there was a bug in `20190122.0.0` but it has been fixed in later releases. If you mean that the bug is how `vagrant box update` works, then Seravo cannot fix it, since that is how Vagrant itself and its built-in commands work. Vagrant won't overwrite existing boxes and start new ones unless the old has first been destroyed by the developer intentionally.

**Comment by luuptekman** [comment]
No, I mean a situation that you can start up vagrant box, if seravo/wordpress box is too old. Don't know if you have any control on that..in Vagrantfile on line 53 you are defining the box version, would updating that line help in here?

**Comment by ottok** [comment]
Yes, we will update that line if there is something that is not backwards compatible, but that line is not used for box updates as such (and there is no way to automatically update the Vagrantfile itself anyway).
